### ISSUE TITLE
Some ideas and a small issue with the R-client

### ISSUE THREAD

**Issue by pgrosu** [googlegenomics/api-client-java#26]
Hi All,

So I started playing with the R and Java client implementations and am very excited about them.  In this post I will cover some aspects I noticed with the R implementation and some ideas I tried out - sorry about the formatting since it's my first time posting on Github:

1)  I really liked the code, but thought that maybe for the Reads resource, there could be a Read class and then when returning Reads they can be performed as a list of Reads, via the searchReads() method.  Below is an example of what I implemented – I just thought classes might be easier to manipulate:

Example of how to run:

  searchReads( sequenceName="chr3", sequenceStart=121458049, sequenceEnd=121459049)

Code:

library("hash")

setClass( Class="Read", representation(
id = "character",
name = "character",
readsetId = "character",
flags = "numeric",
referenceSequenceName = "character",
position = "numeric",
mappingQuality = "numeric",
cigar = "character",
mateReferenceSequenceName = "character",
matePosition = "numeric",
templateLength = "numeric",
originalBases = "character",
alignedBases = "character",
baseQuality = "character",
tags = "hash"
)
)                

searchReads <- function( sequenceName="chr19", sequenceStart=45411941, sequenceEnd=45412079,  readsetId="CJ_ppJ-WCxDxrtDr5fGIhBA=", baseURL="https://www.googleapis.com/genomics/v1beta/",                          pageToken=NULL) {

              readsetIds <- list(readsetId)
                                       
              body <- list(readsetIds=readsetIds,
                           sequenceName=sequenceName,
                           sequenceStart=sequenceStart,
                           sequenceEnd=sequenceEnd,
                           pageToken=pageToken)
							
              result <- POST( paste( baseURL, "reads/search", sep=""),
                              body=toJSON( body ),
                              config( token=google_token ),
                              add_headers("Content-Type"="application/json"))  

              stop_for_status( result )
              
              result.content <- content(result)
              reads <- result.content$reads
              
              list.of.Reads <- list()
              
              for(i in 1:length( reads )) {
                 
                 next.Read <- new("Read")
                 
                   next.Read@name <- reads[[i]]$name
                   next.Read@flags <- reads[[i]]$flags
                   next.Read@position <- reads[[i]]$position
                   next.Read@cigar <- reads[[i]]$cigar
                   next.Read@originalBases <- reads[[i]]$originalBases
                 
                 list.of.Reads <- append(list.of.Reads, next.Read)
                 
              }
              
              list.of.Reads
               
          }

2)  I also started implementing the same for the Dataset resource with a listDatasets() method, but I am unfortunately getting the following error that says that the method is not implemented:

Error in listDatasets() : server error: (501) Not Implemented

Example of how to turn:

listDatasets()

Code:

setClass(Class="Dataset", representation(
                                          id = "character",
                                          projectId = "numeric",
                                          isPublic = "logical"
                                        )
        )

         
listDatasets <- function(object, projectId=NULL, baseURL="https://www.googleapis.com/genomics/v1beta/", 
                                 pageToken=NULL) {
                               
              result <- GET( paste( baseURL, "datasets", sep=""),
                             config( token=google_token ),
                             add_headers("Content-Type"="application/json"))  

              stop_for_status( result )

              result
              
          }

Unless I made a mistake in my implementation - and please correct me if I did - would you know when the list method for Datasets might get implemented?  Are there other methods that are still in the process of getting implemented, and if so which and when might they be ready?  Sorry for the long post.

Thank you,
Paul

**Comment by deflaux** [comment]
Closing this issue - thanks for the discussion!

**Comment by pgrosu** [comment]
Oh wow, that brings up good memories :)
