### ISSUE TITLE
Including more than one version of guava in transitive dependencies causes downstream build failures

### ISSUE THREAD

**Issue by heuermh** [googlegenomics/api-client-java#63]
It appears that more than one version of guava is present in the transitive dependencies for api-client-java

```bash
$ mvn install
...
[INFO] --- maven-dependency-plugin:2.8:copy-dependencies (copy-dependencies) @ genomics-tools-client-java ---
...
[INFO] Copying guava-jdk5-13.0.jar to api-client-java/target/lib/guava-jdk5-13.0.jar
[INFO] Copying guava-17.0.jar to api-client-java/target/lib/guava-17.0.jar
```

This caused a build failure in a downstream project
```bash
$ mvn compile
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] Foo.java:[110,47] cannot find symbol
  symbol:   method splitToList(java.lang.String)
  location: class com.google.common.base.Splitter
[ERROR] Bar.java:[51,27] cannot find symbol
  symbol:   method <C>all()
  location: class com.google.common.collect.Range
...
```

Here's a portion of the dependency tree
```bash
$ mvn dependency:tree
...
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli)
[INFO] +- com.google.apis:google-api-services-genomics:jar:v1beta2-rev13-1.19.0:compile
[INFO] |  \- com.google.api-client:google-api-client:jar:1.19.0:compile
[INFO] |     +- com.google.oauth-client:google-oauth-client:jar:1.19.0:compile
[INFO] |     |  \- com.google.http-client:google-http-client:jar:1.19.0:compile
[INFO] |     |     \- org.apache.httpcomponents:httpclient:jar:4.0.1:compile
[INFO] |     |        +- org.apache.httpcomponents:httpcore:jar:4.0.1:compile
[INFO] |     |        \- commons-logging:commons-logging:jar:1.1.1:compile
[INFO] |     +- com.google.http-client:google-http-client-jackson2:jar:1.19.0:compile
[INFO] |     \- com.google.guava:guava-jdk5:jar:13.0:compile
[INFO] +- com.google.code.findbugs:jsr305:jar:3.0.0:compile
[INFO] +- com.google.guava:guava:jar:17.0:compile
```

I can work around this using exclusions
```xml
      <dependency>
        <groupId>com.google.apis</groupId>
        <artifactId>google-api-services-genomics</artifactId>
        <version>v1beta2-rev13-1.19.0</version>
        <exclusions>
          <exclusion>
            <groupId>com.google.guava</groupId>
            <artifactId>guava-jdk5</artifactId>
          </exclusion>
          <exclusion>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
          </exclusion>
        </exclusions>
      </dependency>
```

but it would be preferable if this were resolved here.  Updating to guava 18.0 could also be a nice side effect.

**Comment by cassiedoll** [comment]
@heuermh if you send over a PR for this I'll merge it right away. Otherwise this will go into my queue :)

**Comment by cassiedoll** [comment]
ps - thanks for letting us know!

**Comment by heuermh** [comment]
The pull request above fixes the downstream build problem for me and continues to pass unit tests.  I can't say that this won't cause problems at runtime however.

**Comment by heuermh** [comment]
Thanks!

**Comment by GitTom** [comment]
This didn't cause me a problem in Eclipse, but when I switched to AS/Gradle Guava became a nuisance (eg. NoSuchMethod exceptions at runtime).

Getting rid of anything that used Google Collections was a first step.

Here's some SO post about the Guava vs. Guava5 conflict issues:
http://stackoverflow.com/questions/25792398/gradle-transitive-dependency-exclusion-is-not-working-as-expected-how-do-i-get
http://stackoverflow.com/questions/25984426/android-studio-multiple-dex-files-gradle-error/26691733  

I would also note that google-oauth-client library also appears to use guava-jdk5, so, while it would be really great if api-client could be switched to regular guava, it would be better to make sure of same for the other google client libraries since they are often used together.

**Comment by GitTom** [comment]
Also, I don't think that using the JDK5 variant is a good solution as it appears it is not being maintained.  Guava was bumped to 18.0 almost a year ago, but there is no 18 for JDK5 (based on maven.org).
