### ISSUE TITLE
Please update pom.xml and the genomics-tools-client-java-v1beta2.jar file

### ISSUE THREAD

**Issue by pgrosu** [googlegenomics/api-client-java#65]
Hi Cassie,

Please update [line 114 of the pom.xml file](https://github.com/googlegenomics/api-client-java/blob/master/pom.xml#L114) to the following, in order to take advantage of `Contig` implementation from [utils-java](https://github.com/googlegenomics/utils-java/blob/master/src/main/java/com/google/cloud/genomics/utils/Contig.java):

```
<version>v1beta2-0.19</version>
```

Also if you could update the Jar file at the following location with the new classes, that would be great - it's a little out of date:

https://github.com/googlegenomics/api-client-java/blob/master/genomics-tools-client-java-v1beta2.jar

Thanks,
Paul

**Comment by cassiedoll** [comment]
@deflaux will take care of you! (or find someone who will :)

**Comment by pgrosu** [comment]
Thanks Nicole/Cassie!  Cassie, I gotta say I like your sense of humor :)

Thanks,
~p
